In [25]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix as cm
import random
import warnings
warnings.filterwarnings("ignore")

In [2]:
train_data = pd.read_csv("fashion-mnist_train.csv")
train_data.head()

label  pixel1  pixel2  pixel3  ...  pixel781  pixel782  pixel783  pixel784
0      2       0       0       0  ...         0         0         0         0
1      9       0       0       0  ...         0         0         0         0
2      6       0       0       0  ...         0         0         0         0
3      0       0       0       0  ...         0         0         0         0
4      3       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [11]:
train_data.shape

(60000, 785)

In [8]:
train_data['label'].unique()

array([2, 9, 6, 0, 3, 4, 5, 8, 7, 1])

In [10]:
labelDecoding = ['T-shirt/top','Trouser','Pullover','Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
for i in range(0,10):
    print("For", i, "th Value:", labelDecoding[i])

For 0 th Value: T-shirt/top
For 1 th Value: Trouser
For 2 th Value: Pullover
For 3 th Value: Dress
For 4 th Value: Coat
For 5 th Value: Sandal
For 6 th Value: Shirt
For 7 th Value: Sneaker
For 8 th Value: Bag
For 9 th Value: Ankle boot


In [12]:
test_data = pd.read_csv("fashion-mnist_test.csv")
test_data.head()

label  pixel1  pixel2  pixel3  ...  pixel781  pixel782  pixel783  pixel784
0      0       0       0       0  ...         0         0         0         0
1      1       0       0       0  ...         0         0         0         0
2      2       0       0       0  ...        31         0         0         0
3      2       0       0       0  ...       222        56         0         0
4      3       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [13]:
test_data.shape

(10000, 785)

In [33]:
y_test = test_data.iloc[:,0]
y_test.head()

0    0
1    1
2    2
3    2
4    3
Name: label, dtype: int64

In [18]:
def BaggingAlgorithm(trainD, testD, number_of_tree):
    
    var = 'Tree'
    model = DecisionTreeClassifier()
    treeDF = pd.DataFrame()
    
    for i in range(number_of_tree):
        
        title = var + " " + str(number_of_tree)
        random_number = random.randint(393,785)
        random_data = trainD.sample(frac = 1.0, replace = True)
        X_train = random_data.iloc[:,1:random_number]
        y_train = random_data.iloc[:,0]
        
        X_test = testD.iloc[:,1:random_number]
        
        model.fit(X_train,y_train)
        y_pred = model.predict(X_test)
        
        treeDF[title] = y_pred
        
    return treeDF

In [21]:
tree1 = BaggingAlgorithm(train_data,test_data,1)
cm(y_pred=tree1,y_true=y_test)

array([[678,   7,  40,  45,  21,   5, 187,   1,  15,   1],
       [ 18, 914,   7,  42,   6,   2,   8,   1,   2,   0],
       [ 38,   8, 604,  45, 158,   0, 137,   0,   9,   1],
       [ 46,  56,  32, 754,  51,   2,  52,   0,   6,   1],
       [ 14,   2, 140,  63, 622,   1, 149,   0,   9,   0],
       [  1,   0,   1,   3,   1, 863,   0,  79,  18,  34],
       [144,   9, 131,  56, 133,   2, 497,   0,  27,   1],
       [  0,   0,   0,   0,   0,  57,   0, 847,   7,  89],
       [ 15,   6,  18,  12,  10,  16,  29,   9, 882,   3],
       [  0,   0,   0,   0,   0,  27,   0,  91,   9, 873]])

In [23]:
tree10 = BaggingAlgorithm(train_data,test_data,10)
final_value = tree10.mode(axis=1).iloc[:,0]
cm(final_value,y_test)

array([[705,  11,  45,  42,  16,   2, 142,   0,  15,   1],
       [ 16, 930,   3,  63,   7,   3,  11,   0,   3,   0],
       [ 42,   6, 595,  30, 158,   3, 141,   0,  11,   2],
       [ 42,  30,  42, 767,  55,   3,  57,   0,   5,   1],
       [ 14,   7, 137,  54, 587,   0, 137,   0,  14,   0],
       [  1,   1,   1,   2,   1, 862,   2,  82,   9,  35],
       [152,  13, 163,  32, 170,   2, 491,   0,  30,   1],
       [  0,   0,   0,   0,   0,  84,   0, 815,   4, 100],
       [ 27,   1,  13,   6,   5,  12,  17,   3, 908,   1],
       [  1,   1,   1,   4,   1,  29,   2, 100,   1, 859]])

In [ ]:
tree100 = BaggingAlgorithm(train_data,test_data,100)
final_value = tree10.mode(axis=1).iloc[:,0]
cm(final_value,y_test

In [26]:
#Neural Network
X_train = train_data.iloc[:,1:].values
X_test = test_data.iloc[:,1:].values

y_train = train_data.iloc[:,0].values
y_train = np_utils.to_categorical(y_train, num_classes=10)

In [28]:
model = Sequential()

model.add(Dense(output_dim = 64, init = 'uniform', activation = 'relu', input_dim = 784))

model.add(Dense(output_dim = 32, init = 'uniform', activation = 'relu'))

model.add(Dense(output_dim = 10, init = 'uniform', activation = 'softmax'))

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics= ['accuracy'])

In [32]:
model.fit(X_train,y_train, epochs= 40, batch_size= 128)

y_pred = model.predict(X_test)

Epoch 1/40
60000/60000 [==============================] - 6s 108us/step - loss: 0.2012 - acc: 0.9249
Epoch 2/40
60000/60000 [==============================] - 6s 96us/step - loss: 0.1897 - acc: 0.9294
Epoch 3/40
60000/60000 [==============================] - 6s 94us/step - loss: 0.1940 - acc: 0.9282
Epoch 4/40
60000/60000 [==============================] - 5s 91us/step - loss: 0.1893 - acc: 0.9293
Epoch 5/40
60000/60000 [==============================] - 6s 104us/step - loss: 0.1947 - acc: 0.9277
Epoch 6/40
60000/60000 [==============================] - 12s 194us/step - loss: 0.1892 - acc: 0.9295
Epoch 7/40
60000/60000 [==============================] - 7s 114us/step - loss: 0.1944 - acc: 0.9285
Epoch 8/40
60000/60000 [==============================] - 6s 103us/step - loss: 0.2001 - acc: 0.9265
Epoch 9/40
60000/60000 [==============================] - 14s 232us/step - loss: 0.1852 - acc: 0.9304
Epoch 10/40
60000/60000 [==============================] - 7s 118us/step - loss: 0.1864 - ac

In [37]:
newDataframe = pd.DataFrame()
for i in range(0,10):
    newDataframe[str(i)] = y_pred[:,i]
    
final_answer = newDataframe.idxmax(axis = 1).astype(int)

In [38]:
cm(final_answer, y_test)

array([[819,   4,  18,  30,   0,   0, 146,   0,  10,   1],
       [  3, 984,   4,  17,   3,   0,   2,   0,   1,   0],
       [ 12,   1, 833,  12, 144,   1,  83,   0,   4,   0],
       [ 17,   8,  15, 893,  34,   0,  29,   1,   1,   1],
       [  1,   1,  50,  22, 768,   0,  46,   0,   4,   0],
       [  2,   0,   0,   0,   0, 935,   0,  21,   5,   4],
       [141,   0,  75,  21,  48,   1, 687,   0,  11,   0],
       [  0,   1,   0,   0,   0,  34,   0, 947,   2,  37],
       [  5,   1,   5,   5,   2,   5,   7,   0, 961,   0],
       [  0,   0,   0,   0,   1,  24,   0,  31,   1, 957]])